name: "Check formatting"
on: 
  pull_request: 
    types: [opened, synchronize]
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: cbrevik/test-action@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

