name: "Check spelling"
on: 
  pull_request: 
    types: [opened]
    
jobs:
  hello:
    runs-on: macOS-latest
    steps:
    - uses: varianter/spellcheck-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        main-comment: "Hi there some misspellings methinks 🛠"
        language: "en_US"
        ignored_words: "probot;wat"
