name: "LETS DO THIS"
on: [pull_request, check_run, check_suite]
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: cbrevik/test-action@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
