name: "LETS DO THIS"
on: 
- pull_request:
    types: [opened, synchronize]
- check_run:
    types: [requested_action]
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: cbrevik/test-action@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
